### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by davidbrochart** [jupyter/nbclient#31] opened 2020-02-28 08:42 UTC
When do you plan to make a release? We need one in order to have async execution in Voila (https://github.com/voila-dashboards/voila/pull/541).
Also, I saw that nbclient was released in PyPI (https://pypi.org/project/nbclient/#history) but not in the GitHub repo.

**Comment by MSeal** [comment] 2020-02-28 18:34
There's one issue that came up internally here in testing papermill 2.0 and nbclient around nested papermill calls from subprocesses that might be related to nbclient holding onto kernel state too long. I'm going to test for that more this weekend and submit a fix if it is the root cause (haven't made an issue for it yet). Other than that I think we can do a release unless there's anything you know about that we need to address first.

> Also, I saw that nbclient was released in PyPI (https://pypi.org/project/nbclient/#history) but not in the GitHub repo.

Whoops, fixed now.

**Comment by choldgraf** [comment] 2020-02-28 18:40
I am also not super sure whether or not I've uncovered a bug in #7 - if that's a bug, it should probably be a blocker on a release as well

**Comment by MSeal** [comment] 2020-02-28 18:41
I can dig into that one as well, I think it's likely a config issue but yes we should figure that out first

**Comment by MSeal** [comment] 2020-03-02 04:28
I got a little sick this weekend, will dig in and help get a release out after I'm feeling better.

**Comment by choldgraf** [comment] 2020-03-02 04:46
@MSeal don't sweat it, and I hope you feel better!

**Comment by MSeal** [comment] 2020-03-31 19:51
Release is out finally! Thanks everyone for the hard work

**Closed by MSeal** 2020-03-31 19:51 UTC
Labels: question

**Comment by davidbrochart** [comment] 2020-03-31 19:53
Thanks a lot Matthew!

**Comment by choldgraf** [comment] 2020-03-31 20:27
hooray!!! 🎉🎉🎉

congrats everybody, and thanks @MSeal for pushing us over the finish line :-)

**Comment by davidbrochart** [comment] 2020-04-01 12:54
Do we want to tag on GitHub too? I only see 0.1.0 in https://github.com/jupyter/nbclient/releases

**Comment by MSeal** [comment] 2020-04-01 16:38
Done. I thought I had pushed the tags too but I guess I missed that.

**Comment by choldgraf** [comment] 2020-04-01 16:49
We all owe you a 🍺 @MSeal
